version: '2'
services:
    myretail:
        build: .
        container_name: "myretail"
        image: pavanganti/myretail
        environment:
            - NODE_ENV=development
            - FOO=bar
        ports:
            - 8081:8081
        depends_on:
            - mongodb
    mongodb:
        image: mongo:3.2
        ports:
        - "27017:27017"
        container_name: "mongodb"
        privileged: true
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - "./mongodb:/data/db"
          - "./mongodb/initialize.js:/initialize.js"
        command: >
                 sh -c '
                 sh -c 
                 "mongod --journal &" 
                 && sleep 2 
                 && mongo < initialize.js 
                 && mongod --shutdown 
                 && mongod --auth'