version: '2'
services:
    myretail:
        build: .
        container_name: "myretail"
        image: pavanganti/myretail
        environment:
            - NODE_ENV=development
            - FOO=bar
        ports:
            - 8081:8081
        links:
            - mongo-instance
        depends_on:
            - mongo-instance
    mongo-instance:
        extends:
            file: mongodb.yml
            service: mongo-instance
        